# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terra/wasm/v1beta1/wasm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import gogo_pb2 as gogoproto_dot_gogo__pb2
from proto import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dterra/wasm/v1beta1/wasm.proto\x12\x12terra.wasm.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto"\xc3\x01\n\x06Params\x12\x37\n\x11max_contract_size\x18\x01 \x01(\x04\x42\x1c\xf2\xde\x1f\x18yaml:"max_contract_size"\x12\x35\n\x10max_contract_gas\x18\x02 \x01(\x04\x42\x1b\xf2\xde\x1f\x17yaml:"max_contract_gas"\x12?\n\x15max_contract_msg_size\x18\x03 \x01(\x04\x42 \xf2\xde\x1f\x1cyaml:"max_contract_msg_size":\x08\xe8\xa0\x1f\x01\x98\xa0\x1f\x00"\x87\x01\n\x08\x43odeInfo\x12-\n\x07\x63ode_id\x18\x01 \x01(\x04\x42\x1c\xf2\xde\x1f\x0eyaml:"code_id"\xe2\xde\x1f\x06\x43odeID\x12\'\n\tcode_hash\x18\x02 \x01(\x0c\x42\x14\xf2\xde\x1f\x10yaml:"code_hash"\x12#\n\x07\x63reator\x18\x03 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:"creator""\xf1\x01\n\x0c\x43ontractInfo\x12#\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:"address"\x12#\n\x07\x63reator\x18\x02 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:"creator"\x12\x1f\n\x05\x61\x64min\x18\x03 \x01(\tB\x10\xf2\xde\x1f\x0cyaml:"admin"\x12-\n\x07\x63ode_id\x18\x04 \x01(\x04\x42\x1c\xf2\xde\x1f\x0eyaml:"code_id"\xe2\xde\x1f\x06\x43odeID\x12\x41\n\x08init_msg\x18\x05 \x01(\x0c\x42/\xf2\xde\x1f\x0fyaml:"init_msg"\xfa\xde\x1f\x18\x65ncoding/json.RawMessage:\x04\xe8\xa0\x1f\x01\x42*Z(github.com/terra-money/core/x/wasm/typesb\x06proto3'
)


_PARAMS = DESCRIPTOR.message_types_by_name["Params"]
_CODEINFO = DESCRIPTOR.message_types_by_name["CodeInfo"]
_CONTRACTINFO = DESCRIPTOR.message_types_by_name["ContractInfo"]
Params = _reflection.GeneratedProtocolMessageType(
    "Params",
    (_message.Message,),
    {
        "DESCRIPTOR": _PARAMS,
        "__module__": "terra.wasm.v1beta1.wasm_pb2"
        # @@protoc_insertion_point(class_scope:terra.wasm.v1beta1.Params)
    },
)
_sym_db.RegisterMessage(Params)

CodeInfo = _reflection.GeneratedProtocolMessageType(
    "CodeInfo",
    (_message.Message,),
    {
        "DESCRIPTOR": _CODEINFO,
        "__module__": "terra.wasm.v1beta1.wasm_pb2"
        # @@protoc_insertion_point(class_scope:terra.wasm.v1beta1.CodeInfo)
    },
)
_sym_db.RegisterMessage(CodeInfo)

ContractInfo = _reflection.GeneratedProtocolMessageType(
    "ContractInfo",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTRACTINFO,
        "__module__": "terra.wasm.v1beta1.wasm_pb2"
        # @@protoc_insertion_point(class_scope:terra.wasm.v1beta1.ContractInfo)
    },
)
_sym_db.RegisterMessage(ContractInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z(github.com/terra-money/core/x/wasm/types"
    _PARAMS.fields_by_name["max_contract_size"]._options = None
    _PARAMS.fields_by_name[
        "max_contract_size"
    ]._serialized_options = b'\362\336\037\030yaml:"max_contract_size"'
    _PARAMS.fields_by_name["max_contract_gas"]._options = None
    _PARAMS.fields_by_name[
        "max_contract_gas"
    ]._serialized_options = b'\362\336\037\027yaml:"max_contract_gas"'
    _PARAMS.fields_by_name["max_contract_msg_size"]._options = None
    _PARAMS.fields_by_name[
        "max_contract_msg_size"
    ]._serialized_options = b'\362\336\037\034yaml:"max_contract_msg_size"'
    _PARAMS._options = None
    _PARAMS._serialized_options = b"\350\240\037\001\230\240\037\000"
    _CODEINFO.fields_by_name["code_id"]._options = None
    _CODEINFO.fields_by_name[
        "code_id"
    ]._serialized_options = b'\362\336\037\016yaml:"code_id"\342\336\037\006CodeID'
    _CODEINFO.fields_by_name["code_hash"]._options = None
    _CODEINFO.fields_by_name[
        "code_hash"
    ]._serialized_options = b'\362\336\037\020yaml:"code_hash"'
    _CODEINFO.fields_by_name["creator"]._options = None
    _CODEINFO.fields_by_name[
        "creator"
    ]._serialized_options = b'\362\336\037\016yaml:"creator"'
    _CONTRACTINFO.fields_by_name["address"]._options = None
    _CONTRACTINFO.fields_by_name[
        "address"
    ]._serialized_options = b'\362\336\037\016yaml:"address"'
    _CONTRACTINFO.fields_by_name["creator"]._options = None
    _CONTRACTINFO.fields_by_name[
        "creator"
    ]._serialized_options = b'\362\336\037\016yaml:"creator"'
    _CONTRACTINFO.fields_by_name["admin"]._options = None
    _CONTRACTINFO.fields_by_name[
        "admin"
    ]._serialized_options = b'\362\336\037\014yaml:"admin"'
    _CONTRACTINFO.fields_by_name["code_id"]._options = None
    _CONTRACTINFO.fields_by_name[
        "code_id"
    ]._serialized_options = b'\362\336\037\016yaml:"code_id"\342\336\037\006CodeID'
    _CONTRACTINFO.fields_by_name["init_msg"]._options = None
    _CONTRACTINFO.fields_by_name[
        "init_msg"
    ]._serialized_options = (
        b'\362\336\037\017yaml:"init_msg"\372\336\037\030encoding/json.RawMessage'
    )
    _CONTRACTINFO._options = None
    _CONTRACTINFO._serialized_options = b"\350\240\037\001"
    _PARAMS._serialized_start = 108
    _PARAMS._serialized_end = 303
    _CODEINFO._serialized_start = 306
    _CODEINFO._serialized_end = 441
    _CONTRACTINFO._serialized_start = 444
    _CONTRACTINFO._serialized_end = 685
# @@protoc_insertion_point(module_scope)
